#DataBase Setting
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=kun
spring.datasource.password=gunu91

#
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB

#Spring Security Setting
secret-key=S3cr3tK3y;

#filePath
file.path=E:/workspace/study/fileUpload/
file.url=http://localhost:8080/file/

#JPA Setting
# ddl-auto \uC635\uC158\uC740 DB\uC758 \uBCC0\uD654\uB97C \uACE0\uB824\uD574 \uC790\uB3D9\uC73C\uB85C \uC0DD\uC131,\uBCC0\uACBD,\uC0AD\uC81C\uB97C \uD55C\uB2E4 (\uC635\uC158:  create, create-drop, update, validate, none)
# MySQL\uC758 \uACBD\uC6B0 \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uC758 \uC5D4\uC9C4\uC744 MyISAM, InnoDB\uB85C \uAD6C\uBD84\uD55C\uB2E4
# MyISAM\uC740 \uC608\uC804\uBD80\uD130 \uC0AC\uC6A9\uD55C \uC5D4\uC9C4\uC73C\uB85C \uC18D\uB3C4\uBA74\uC5D0\uC11C \uC7A5\uC810\uC774 \uC788\uC9C0\uB9CC \uB370\uC774\uD130 \uBD88\uACB0\uC131\uC744 \uC81C\uB300\uB85C \uCCB4\uD06C\uD558\uC9C0 \uC54A\uAE30 \uB584\uBB38\uC5D0 \uCD5C\uADFC\uC5D0\uB294 InnoDB\uB97C \uAD8C\uC7A5 \uD55C\uB2E4
# MyISAM\uC740 \uC678\uB798\uD0A4 \uB300\uC2E0 \uC778\uB371\uC2A4\uAC00 \uC0DD\uC131\uB41C\uB2E4
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=info